### ISSUE TITLE
TLS version incompatibility when using latest JDKs with MySQL <8

### ISSUE THREAD

**Issue by rnorth** [mirromutth/r2dbc-mysql#182]
Hi! I've been working on fixing [an issue in Testcontainers' test suite](https://github.com/testcontainers/testcontainers-java/issues/4058), and found a related issue here as well.

https://bugs.openjdk.java.net/browse/JDK-8202343 has disabled TLS1 and TLS1.1 in the latest versions of JDKs, and this seems to be particularly troublesome for connections to legacy versions of MySQL (e.g. 5.6, 5.7).

Following this (quite surprising) change to the JDK, the `SslBridgeHandler` code [here](https://github.com/mirromutth/r2dbc-mysql/blob/main/src/main/java/dev/miku/r2dbc/mysql/client/SslBridgeHandler.java#L195-L212) is now capable of producing an invalid set of TLS protocols when using:

* An up to date OpenJDK, e.g. `1.11.0-11`
* A MySQL server version <=8.0.4 (even though, per [docs](https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-reference-using-ssl.html) and my own testing, >=5.7.28 and >=5.6.46 are capable of using TLS1.2)

With this combination of new and old, `r2dbc-mysql` is choosing to use TLS1.1/TLS1, which quickly fails with:

```
Caused by: javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
```

I'd imagine that a small tweak to the `isEnabledTls1_2` function would allow TLS1.2 to be used with older MySQL versions that can use it, so that the library is less inclined to try to use one of the disabled protocols. It might be good to fail-fast as well, with an informative exception when this incompatibility arises.

**Comment by mp911de** [comment]
It seems that MySQL < 8 doesn't support TLSv1.2 but since in Spring Data JDBC tests broke as well with newer JDK versions on older MySQL versions.

**Comment by rnorth** [comment]
Yes, it seems that TLS1.2 support was added for MySQL >=5.7.28 and >=5.6.46. For my own selfish purposes I've just bumped the version of MySQL we use in our tests (all the way up to 8.x for Testcontainers' R2DBC module). 

Because this change was apparently backported as far back as OpenJDK 7, I bet there will be a fair number of people running outdated versions of MySQL who get caught out by this - in test and in production.

**Comment by mp911de** [comment]
@mirromutth We plan a round of R2DBC service releases for next week. It would be a good opportunity to include this change and a driver release to address that Java change.

**Comment by Bryksin** [comment]
Having the same issue with the latest JDK11

```
dev.miku.r2dbc.mysql.client.MySqlConnectionClosedException: Connection unexpectedly closed
********
javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
```

**Comment by Bryksin** [comment]
Ok got it working, had to upgrade our MySQL from 5.6 to 5.7, as they introduced TSL only in 5.7 and limit it to `TLSv1.2`

Here is AWS RDS MySQL 5.7 props screenshot:
![aws-rds-mysql](https://i.gyazo.com/b52ed04626969a65e1dbba606df9b960.png)

Additionally on the client-side had to set the property `tlsVersion`
```
spring:
  r2dbc:
    username: "****"
    password: "****"
    url: r2dbc:mysql://<host>:<port>/${spring.application.name}
    properties:
      - tlsVersion: TLSv1.2
```

if you use `Liquibase`, u will need to add `enabledTLSProtocols` param too:

```
spring:
  liquibase:
    enabled: true
    url: jdbc:mysql://<host>:<port>/${spring.application.name}?createDatabaseIfNotExist=true&enabledTLSProtocols=TLSv1.2
```

**Comment by charlie-harvey** [comment]
```
spring:
  r2dbc:
    username: "****"
    password: "****"
    url: r2dbc:mysql://<host>:<port>/${spring.application.name}?sslMode=DISABLED
```
If you are actually using TLS there is work to do. I had the problem where I wasn't actually using TLS and it was still complaining. This is how to turn it off.
